<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'שליחת Custom Form',
	'heading' => 'שליחת טופס חדש',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'מסומן',
		'checkbox_unchecked' => 'לא מסומן',
		'submitted_from' => 'הטופס נשלח מאתר אינטרנט: %s',
		'submitted_by' => 'כתובת IP של מבקר: %s',
		'too_many_submissions' => 'בוצעו לאחרונה יותר מדי פעולות שליחה מ-IP זה',
		'failed_to_send_email' => 'שליחת דואר אלקטרוני נכשלה',
		'invalid_reCAPTCHA_private_key' => 'מפתח פרטי לא חוקי של reCAPTCHA.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'סוג שדה לא ידוע \'%s\'.',
		'invalid_form_config' => 'התצורה של השדה \'%s\' אינה חוקית.',
		'unknown_method' => 'פעולת שירות לא ידועה של בקשת שרת'
	),
	'email' => array(
		'from' => 'painter@adobe.com',
		'to' => 'painter@adobe.com'
	),
	'fields' => array(
		'custom_U15660' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'שם',
			'required' => true,
			'errors' => array(
				'required' => 'השדה \'שם\' נדרש.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'כתובת דואר אלקטרוני',
			'required' => true,
			'errors' => array(
				'required' => 'השדה \'כתובת דואר אלקטרוני\' נדרש.',
				'format' => 'השדה \'כתובת דואר אלקטרוני\' כולל כתובת דואר אלקטרוני לא חוקית.'
			)
		),
		'custom_U15669' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'הודעה',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U15673' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'טלפון סלולרי',
			'required' => true,
			'errors' => array(
				'required' => 'השדה \'טלפון סלולרי\' נדרש.'
			)
		),
		'custom_U15680' => array(
			'order' => 5,
			'type' => 'radiogroup',
			'label' => 'קבוצת לחצני אפשרויות',
			'required' => true,
			'optionItems' => array(
				'25 תליונים (50 ש"ח)',
				'50 תליונים (100 ש"ח)'
			),
			'errors' => array(
				'required' => 'השדה \'קבוצת לחצני אפשרויות\' נדרש.',
				'format' => 'לשדה \'קבוצת לחצני אפשרויות\' יש ערך לא חוקי.'
			)
		)
	)
);

process_form($form);
?>
